services:
  mysql:
    image: mysql:8.0
    container_name: error-radar-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: errorradar
      MYSQL_USER: errorradar
      MYSQL_PASSWORD: errorradar
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7.2
    container_name: error-radar-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  redis-data: